name: Selenium Cucumber CI/CD

on:
  push:
    branches: [ main ]  # Runs on push to the main branch
  pull_request:
    branches: [ main ]  # Runs on pull requests to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Runs on Linux; choose based on your needs

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Checks out your code so it can be used by the workflow

      - name: Set up JDK
        uses: actions/setup-java@v4.5.0
        with:
          java-version: 21
          distribution: 'temurin'  # Specify the distribution
          java-package: jdk
          architecture: x64

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Install Dependencies
        run: mvn install  # Installs dependencies and compiles the code

      - name: Run Tests
        run: mvn test  # Executes the test suite

      - name: Copy Extent Report Files
        if: always()  # Ensures report generation even if tests fail
        run: |
          mkdir -p test-reports/HtmlReport &&
          mkdir -p test-reports/PdfReport &&
          cp -r test-reports/HtmlReport/* test-reports/HtmlReport/ &&
          cp -r test-reports/PdfReport/* test-reports/PdfReport/


      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: HtmlReport
          path: test-reports/HtmlReport/  # Uploads HTML report

      - name: Upload PDF Report
        uses: actions/upload-artifact@v4
        with:
          name: PdfReport
          path: test-reports/PdfReport/  # Uploads PDF report
